apiVersion: v2
name: temporal-cloudmc
description: Temporal is a distributed, scalable, durable, and highly available orchestration engine to execute asynchronous long-running business logic in a scalable and resilient way.
home: https://temporal.io/
keywords:
- temporal
- workflow
- orchestration
maintainers:
- name: Temporal Technologies Inc.
  url: https://temporal.io/
sources:
- https://github.com/temporalio/temporal
dependencies:
- name: cassandra
  version: 0.14.3
  repository: https://charts.helm.sh/incubator
  enabled: false
  condition: cassandra.enabled
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 15.1.3
  condition: prometheus.enabled
- name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.17.3
  condition: elasticsearch.enabled
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 5.0.10
  condition: grafana.enabled
type: application
version: 0.24.0
appVersion: 1.21.1
