apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-temporal-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: temporal
  egress:
  - {}
  policyTypes:
  - Egress